### ISSUE TITLE
Something wrong when i use xyz data

### ISSUE THREAD

**Issue by Chuanqi-Zang** [BII-wushuang/Lie-Group-Motion-Prediction#5]
When I set "datatype" as "xyz", I get follow issue, you may forget to set the "chain_idx"

> Traceback (most recent call last):
  File "/home/cz5270/Lie-Group-Motion-Prediction/src/motion_prediction.py", line 316, in <module>
    tf.app.run()
  File "/home/cz5270/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/cz5270/anaconda3/envs/tf/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/cz5270/anaconda3/envs/tf/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/cz5270/Lie-Group-Motion-Prediction/src/motion_prediction.py", line 218, in main
    train()
  File "/home/cz5270/Lie-Group-Motion-Prediction/src/motion_prediction.py", line 44, in train
    prediction = models.seq2seq(x, dec_in, config, True)
  File "/home/cz5270/Lie-Group-Motion-Prediction/src/models.py", line 102, in seq2seq
    outputs, states = tf.contrib.legacy_seq2seq.rnn_decoder(dec_in, enc_state, dec_cell, loop_function=lf)
  File "/home/cz5270/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py", line 152, in rnn_decoder
    output, state = cell(inp, state)
  File "/home/cz5270/Lie-Group-Motion-Prediction/src/models.py", line 184, in __call__
    output = xyz_resize(output, self.config)
  File "/home/cz5270/Lie-Group-Motion-Prediction/src/models.py", line 374, in xyz_resize
    index = config.chain_idx
AttributeError: 'train_Config' object has no attribute 'chain_idx'

**Comment by AliceKirisame** [comment]
> When I set "datatype" as "xyz", I get follow issue, you may forget to set the "chain_idx"
> 
> > Traceback (most recent call last):
> > File "/home/cz5270/Lie-Group-Motion-Prediction/src/motion_prediction.py", line 316, in 
> > tf.app.run()
> > File "/home/cz5270/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
> > _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
> > File "/home/cz5270/anaconda3/envs/tf/lib/python3.7/site-packages/absl/app.py", line 300, in run
> > _run_main(main, args)
> > File "/home/cz5270/anaconda3/envs/tf/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
> > sys.exit(main(argv))
> > File "/home/cz5270/Lie-Group-Motion-Prediction/src/motion_prediction.py", line 218, in main
> > train()
> > File "/home/cz5270/Lie-Group-Motion-Prediction/src/motion_prediction.py", line 44, in train
> > prediction = models.seq2seq(x, dec_in, config, True)
> > File "/home/cz5270/Lie-Group-Motion-Prediction/src/models.py", line 102, in seq2seq
> > outputs, states = tf.contrib.legacy_seq2seq.rnn_decoder(dec_in, enc_state, dec_cell, loop_function=lf)
> > File "/home/cz5270/anaconda3/envs/tf/lib/python3.7/site-packages/tensorflow/contrib/legacy_seq2seq/python/ops/seq2seq.py", line 152, in rnn_decoder
> > output, state = cell(inp, state)
> > File "/home/cz5270/Lie-Group-Motion-Prediction/src/models.py", line 184, in **call**
> > output = xyz_resize(output, self.config)
> > File "/home/cz5270/Lie-Group-Motion-Prediction/src/models.py", line 374, in xyz_resize
> > index = config.chain_idx
> > AttributeError: 'train_Config' object has no attribute 'chain_idx'

Hello, I also encountered this problem. Have you solved it?

**Comment by BII-wushuang** [comment]
The xyz_resize function is an artifact of some previous trial tests and has since been obsolete. I have removed this from the latest commit.
